/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassDlg.java
 *
 * Created on 2011. 1. 10, 오후 2:38:24
 */

package viewer;

import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author KHJ
 */
public class ClassDlg extends javax.swing.JDialog {

    private static ClassDlg dlg;
    private static int[] result;

    public static int[] showDialog(java.awt.Frame parent, boolean modal, String[] str) {
        dlg = new ClassDlg(parent, modal, str);
        dlg.setTitle("Class Chooser");
        dlg.selectLabel.setText("Select the classes");
        RefineryUtilities.centerFrameOnScreen(dlg);
        dlg.setVisible(true);

        return result;
    }

    public static void showDialogOnlyStr(java.awt.Frame parent, boolean modal, String[] str) {
        dlg = new ClassDlg(parent, modal, str);
        dlg.setTitle("Pair List");
        dlg.selectLabel.setText("Resulted Pairs");
        RefineryUtilities.centerFrameOnScreen(dlg);
        dlg.setVisible(true);
    }

    public static void showDialogOnlyStr2(java.awt.Frame parent, boolean modal, String[] str) {
        dlg = new ClassDlg(parent, modal, str);
        dlg.setTitle("Feature List");
        dlg.selectLabel.setText("Resulted Features");
        RefineryUtilities.centerFrameOnScreen(dlg);
        dlg.setVisible(true);
    }

    public static void showDialogOnlyInt(java.awt.Frame parent, boolean modal, int[] order) {
        String[] str = new String[order.length];
        for(int i = 0; i < str.length; i++) {
            str[i] = "" + order[i];
        }
        dlg = new ClassDlg(parent, modal, str);
        dlg.setTitle("Feature Order");
        dlg.selectLabel.setText("Resulted Orders");
        RefineryUtilities.centerFrameOnScreen(dlg);
        dlg.setVisible(true);
    }

    /** Creates new form ClassDlg */
    private ClassDlg(java.awt.Frame parent, boolean modal, String[] str) {
        super(parent, modal);
        initComponents();
        initVariables(str);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        okPanel = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        selectLabel = new javax.swing.JLabel();
        listScrollPane = new javax.swing.JScrollPane();
        classList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Class Chooser");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("classDlg"); // NOI18N
        setResizable(false);

        okPanel.setLayout(new java.awt.GridBagLayout());

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 45, 10, 51);
        okPanel.add(okBtn, gridBagConstraints);

        selectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectLabel.setText("Select the classes");

        listScrollPane.setViewportView(classList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(selectLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(okPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
        result = classList.getSelectedIndices();
        viewer.ClassDlg.dlg.setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed


    private void initVariables(String[] str) {
        this.classList.setListData(str);
    }

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClassDlg dialog = new ClassDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList classList;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JButton okBtn;
    private javax.swing.JPanel okPanel;
    private javax.swing.JLabel selectLabel;
    // End of variables declaration//GEN-END:variables

}
