/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PredictionDlg.java
 *
 * Created on 2011. 5. 2, 오후 3:58:03
 */

package viewer;

import javax.swing.JTable;
import javax.swing.JOptionPane;

/**
 *
 * @author KHJ
 */
public class PredictionDlg extends javax.swing.JDialog {

    private JTable[] table;
    private viewer.OpenFileChooser ofc;
    private boolean isROC;
    private viewer.MainFrame mf;

    /** Creates new form PredictionDlg */
    public PredictionDlg(viewer.MainFrame mf, boolean modal, JTable[] t, boolean isROC) {
        super(mf, modal);
        this.mf = mf;
        table = t;
        this.isROC = isROC;
        initComponents();
        initVariables();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeBtnGrp = new javax.swing.ButtonGroup();
        typePanel = new javax.swing.JPanel();
        newBtn = new javax.swing.JRadioButton();
        fromfileBtn = new javax.swing.JRadioButton();
        importantPanel = new javax.swing.JPanel();
        clstrNumPanel = new javax.swing.JPanel();
        clstrNumText = new javax.swing.JTextField();
        majorityNumPanel = new javax.swing.JPanel();
        majorityNumText = new javax.swing.JTextField();
        decisionPanel = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prediction INFO.");
        setResizable(false);

        typePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 1, 12))); // NOI18N
        typePanel.setLayout(new java.awt.GridLayout());

        typeBtnGrp.add(newBtn);
        newBtn.setSelected(true);
        newBtn.setText("New proceed");
        newBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typePanel.add(newBtn);

        typeBtnGrp.add(fromfileBtn);
        fromfileBtn.setText("Perform from file");
        fromfileBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fromfileBtnStateChanged(evt);
            }
        });
        typePanel.add(fromfileBtn);

        importantPanel.setLayout(new java.awt.GridLayout());

        clstrNumPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cluster number", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 1, 12))); // NOI18N
        clstrNumPanel.setLayout(new java.awt.GridLayout());
        clstrNumPanel.add(clstrNumText);

        importantPanel.add(clstrNumPanel);

        majorityNumPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Majority vote number", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 1, 12))); // NOI18N
        majorityNumPanel.setLayout(new java.awt.GridLayout());
        majorityNumPanel.add(majorityNumText);

        importantPanel.add(majorityNumPanel);

        decisionPanel.setLayout(new java.awt.GridLayout());

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        decisionPanel.add(okBtn);

        cancelBtn.setText("Cancle");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        decisionPanel.add(cancelBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importantPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(typePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(decisionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(typePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decisionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initVariables() {
        if(isROC == true) {
            newBtn.setEnabled(false);
            fromfileBtn.setSelected(true);
        }
    }

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ofc = new viewer.OpenFileChooser();
        String[] info = new String[4];
        info[1] = clstrNumText.getText();       //cluster number
        info[2] = majorityNumText.getText();    //majority vote number
        if(newBtn.isSelected() == true) {
            info[0] = ofc.openChooser(mf, 1);    //path
            if(!info[0].equals("")) {
                String s = (String)JOptionPane.showInputDialog(
                    this,
                    "File name ?",
                    "Write cf file name",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    null,
                    "");
                info[0] = info[0] + "/" + s + ".cf";
            }
            info[3] = "new";
        }
        else {
            info[0] = ofc.openChooser(mf, 2);    //path
            info[3] = "old";
        }

        String str = "";

        if(!info[0].equals("")) {
            if(isROC == true) {
                str = new prediction.ROCCurve(table, mf, info[0]).getResultStr();
            }
            else {
                str = new prediction.LOOCV(table, mf, info).getResultStr();
            }

            JOptionPane.showMessageDialog(mf,
                str,
                "Classification Accuracy(LOOCV)",
                JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_okBtnActionPerformed

    private void fromfileBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fromfileBtnStateChanged
        // TODO add your handling code here:
        if(fromfileBtn.isSelected() == true) {
            clstrNumText.setEnabled(false);
            clstrNumText.setText("");
            majorityNumText.setEnabled(false);
            majorityNumText.setText("");
        }
        else {
            clstrNumText.setEnabled(true);
            majorityNumText.setEnabled(true);
        }
    }//GEN-LAST:event_fromfileBtnStateChanged

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PredictionDlg dialog = new PredictionDlg(new javax.swing.JFrame(), false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel clstrNumPanel;
    private javax.swing.JTextField clstrNumText;
    private javax.swing.JPanel decisionPanel;
    private javax.swing.JRadioButton fromfileBtn;
    private javax.swing.JPanel importantPanel;
    private javax.swing.JPanel majorityNumPanel;
    private javax.swing.JTextField majorityNumText;
    private javax.swing.JRadioButton newBtn;
    private javax.swing.JButton okBtn;
    private javax.swing.ButtonGroup typeBtnGrp;
    private javax.swing.JPanel typePanel;
    // End of variables declaration//GEN-END:variables

}
